// <auto-generated />
using ECommerceShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceShop.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240324164847_AddQuantity")]
    partial class AddQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceShop.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Phone",
                            Photo = "Phone.jpg",
                            Price = 999.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = "2",
                            Name = "Camera",
                            Photo = "Camera.jpg",
                            Price = 899.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = "3",
                            Name = "TV",
                            Photo = "TV.jpg",
                            Price = 699.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = "4",
                            Name = "Car",
                            Photo = "Car.jpg",
                            Price = 499.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = "5",
                            Name = "Laptop",
                            Photo = "Laptop.jpg",
                            Price = 499.99m,
                            Quantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
